spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: company


  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none

    show-sql: true