spring:
  main:
    allow-circular-references: true
    shell:
      interactive:
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  data:
    mongodb:
      database: library

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none

  batch:
    job:
      enabled: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true









