DROP SEQUENCE IF EXISTS BOOKS_SEQ_ID;
DROP SEQUENCE IF EXISTS COMMENT_SEQ_ID;
DROP TABLE IF EXISTS BOOKS_GENRE;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRE;
