CREATE SEQUENCE SEQ_ID;

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID      BIGINT PRIMARY KEY,
    NAME    VARCHAR(255),
    SURNAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(255),
    GENRE_ID   BIGINT,
    AUTHORS_ID BIGINT,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID),
    FOREIGN KEY (AUTHORS_ID) REFERENCES AUTHORS (ID)
);
