spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false

  springdoc:
    api-docs:
      path: /api-docs

  main:
    allow-circular-references: true

server:
    port: 8888
