/*DROP TABLE IF EXISTS FILTER_CURRENCY;
CREATE TABLE FILTER_CURRENCY(
        ID BIGINT PRIMARY KEY,
         NAME VARCHAR(255),
         NAME_DECODING VARCHAR(255)

);

DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY(
                         CURRENCY_DATE DATE,
                         CURRENCY_TYPE VARCHAR(255),
                         CURRENCY_VALUE number
);

 */